version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["./run.py"]
    image: templastic/python3-django
    restart: unless-stopped
    volumes:
      - ./src:/app
